apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lucaschaves
  name: project2-pv2-lucaschaves
spec:
  storageClassName: default-storage-class-lucaschaves
  selector:
    matchLabels:
      namespace: lucaschaves
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: project2-pv2-lucaschaves